In [3]:
#1
import numpy as np

In [2]:
#2
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#3
null_vector=np.zeros(10)
null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
#4
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
#5
vector=np.arange(0,9).reshape((3,3))
vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
 #6
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [5]:
#7
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#8
output=np.random.random((3,3,3))
output

In [ ]:
#9
a=np.random.rand(10,10)
min=np.min(a)
max=np.max(a)
print(min,max)

In [ ]:
#10
a=np.random.rand(30)
mean=np.mean(a)
mean

In [ ]:
#11
diagonal_values = [1, 2, 3, 4]
matrix= np.diag(diagonal_values, k=-1)
matrix

In [ ]:
#12
matrix=np.random.rand(5,5)
mean=np.mean(matrix)
std=np.std(matrix)
normalized_matrix=(matrix-mean)/std
normalized_matrix

In [22]:
matrix1=np.random.random((5,5))
matrix1_new=np.random.normal(0,1,(5,5))
matrix1_new

array([[-1.15316833,  0.3416142 ,  0.08847281,  0.02344683, -1.48247512],
       [-0.59465132, -0.07718346,  0.05751353,  1.11941023,  0.0493333 ],
       [ 0.44931443,  1.02433947,  0.34253654, -0.1660148 ,  0.10310645],
       [-0.08385181,  0.15560781,  0.70066936,  0.79270061,  1.52906898],
       [ 2.00055957, -0.15627931, -1.45740169,  0.63517837, -1.4890455 ]])

In [ ]:
#13
a_1= ([1, 2, 3, 4, 5])
a_2= ([4, 5, 6, 7, 8])
common_values=np.intersect1d(a_1,a_2)
common_values

In [ ]:
#14
list=np.random.rand(10)
new=np.sort(list)
new

In [ ]:
#15
list=np.random.rand(10)
max_value=np.max(list)
index_max=np.argmax(max_value)
list[index_max]=0
list

In [25]:
#16
random=np.random.randint(0,10,(3,3))
new_array=np.mean(random,keepdims=True,axis=1)
new_array

array([[5.66666667],
       [3.33333333],
       [4.33333333]])

In [9]:
#18
array=np.random.randint(1,10,(5,3))
print(array)
new_array=np.where(array>4,array**2,array)
new_array

[[1 7 6]
 [6 5 1]
 [6 5 5]
 [2 6 5]
 [9 8 9]]


array([[ 1, 49, 36],
       [36, 25,  1],
       [36, 25, 25],
       [ 2, 36, 25],
       [81, 64, 81]])

In [28]:
#17
import numpy as np


Z = np.arange(10000)
partitioned_array = np.partition(Z, 5)
   
n_largest_values = partitioned_array[5:]
n_largest_values

    

array([   5,    6,    7, ..., 9997, 9998, 9999])