In [1]:
#1
import numpy as np

In [3]:
#2
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#3
null_vector=np.zeros(10)
null_vector[4]=1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
#4
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [11]:
#5
vector=np.arange(0,9).reshape((3,3))
vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
 #6
    np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [14]:
#7
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#8
output=np.random.random((3,3,3))
output

array([[[0.47063462, 0.34257686, 0.19242265],
        [0.93824059, 0.95298046, 0.84894235],
        [0.91051581, 0.94281294, 0.50704505]],

       [[0.61702266, 0.83104609, 0.35420023],
        [0.0092097 , 0.46892108, 0.69554463],
        [0.77618717, 0.41374236, 0.94300945]],

       [[0.51606234, 0.62435329, 0.49788495],
        [0.92166019, 0.34238486, 0.25144073],
        [0.07674303, 0.32799602, 0.58776323]]])

In [24]:
#9
a=np.random.rand(10,10)
min=np.min(a)
max=np.max(a)
print(min,max)

0.0006484444299575953 0.9971309124679026


In [28]:
#10
a=np.random.rand(30)
mean=np.mean(a)
mean

0.5825990789343898

In [31]:
#11
diagonal_values = [1, 2, 3, 4]
matrix= np.diag(diagonal_values, k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [36]:
#12
matrix=np.random.rand(5,5)
mean=np.mean(matrix)
std=np.std(matrix)
normalized_matrix=(matrix-mean)/std
normalized_matrix

array([[ 0.92785745, -1.09567959, -0.69503525, -1.64202004, -1.37030747],
       [-0.71896809,  1.19761706, -0.22540381,  0.82723239,  1.04185743],
       [ 0.32512359, -1.06973791, -0.87798306,  1.41970763,  0.10531864],
       [-0.88914724,  1.11914378, -0.08348031,  0.4585077 ,  0.26043213],
       [-1.67728684,  1.79104878,  1.01564031, -0.65143317,  0.5069959 ]])

In [5]:
#13
a_1= ([1, 2, 3, 4, 5])
a_2= ([4, 5, 6, 7, 8])
common_values=np.intersect1d(a_1,a_2)
common_values

array([4, 5])

In [8]:
#14
list=np.random.rand(10)
new=np.sort(list)
new

array([0.00624627, 0.11078946, 0.12154806, 0.29471449, 0.53285851,
       0.54282407, 0.56333346, 0.59647958, 0.6960599 , 0.83438287])

In [11]:
#15
list=np.random.rand(10)
max_value=np.max(list)
index_max=np.argmax(max_value)
list[index_max]=0
list

array([0.        , 0.71531267, 0.73275965, 0.93506648, 0.41546842,
       0.6610313 , 0.71808706, 0.32440306, 0.51087956, 0.92035138])

In [ ]:
#16